# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'conse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for conse
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'ObjectMapper', '~> 3.1'
  pod 'SwiftyJSON'

  target 'conseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'conseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
